repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        language: system
      - id: ruff-format
        language: system

  - repo: local
    hooks:
      - id: prettier
        name: prettier (npx)
        entry: npx prettier --write
        language: system
        pass_filenames: true
        files: '\.(md|json|ya?ml|css|html|js|jsx|ts|tsx)$'

exclude: |
  (?x)^(
    \.venv/|
    node_modules/|
    (.*?/)?site-packages/|
    (.*?/)?\.dist-info/|
    alembic/|
    \.pre-commit-cache/
  )
