name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pyright pytest

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (pyright)
        run: pyright

      - name: Test
        env:
          TESTING: "1"
        run: pytest -q
