name: Smoke
on:
  push:
    branches: [next-steps, main]
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Launch API (background)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          nohup uvicorn fantasy_stocks.main:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          sleep 2
      - name: Smoke
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python smoke_mvp.py
      - name: Upload API logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uvicorn-log
          path: uvicorn.log
